version: "3.2"
services:
  wepy_server:
    build: .
    restart: "no"
    command: /bin/bash -c "invenio run --host 0.0.0.0"
    networks:
      - proxy
    environment:
      - FLASK_DEBUG=1
    volumes:
      - /code/modules/wxpy-index/.eggs
      - /code/modules/wxpy-index/wxpy_index.egg-info
      - ./modules:/code/modules
    depends_on:
      - redis

  redis:
    image: redis

networks:
  proxy:
    external: true
      