version: "3.2"
services:
  wepy_server:
    build: .
    container_name: wepy_server
    restart: "no"
    command: /bin/bash -c "invenio run --host 0.0.0.0 && celery worker -A invenio_app.celery -l DEBUG"
    networks:
      - proxy
      - back
    ports:
      - "127.0.0.1:80:5000"
    environment:
      - FLASK_DEBUG=1
      - INVENIO_REDIS_HOST=wepy_redis
      - INVENIO_CACHE_REDIS_URL=redis://wepy_redis:6379/1
      - INVENIO_CACHE_DEFAULT_TIMEOUT=3600
      - INVENIO_POSTGRESQL_HOST=db
      - INVENIO_POSTGRESQL_DBNAME=wepy
      - INVENIO_POSTGRESQL_DBUSER=wepy
      - INVENIO_POSTGRESQL_DBPASS=wepy!1234
      - INVENIO_SQLALCHEMY_DATABASE_URI=postgresql://wepy:wepy!1234@db/wepy
    volumes:
      - /code/modules/wxpy-index/.eggs
      - /code/modules/wxpy-index/wxpy_index.egg-info
      - ./modules:/code/modules
      - ./entrypoint.sh:/code/entrypoint.sh
    depends_on:
      - db
      - redis

  redis:
    image: redis
    restart: always
    container_name: wepy_redis
    networks:
      - back

  db:
    image: postgres:11-alpine
    restart: always
    container_name: wepy_db
    environment:
      - POSTGRES_PASSWORD=wepy!1234
      - POSTGRES_USER=wepy
      - POSTGRES_DB=wepy
    networks:
      - back

networks:
  proxy:
    external: true
  back:
      